### ISSUE TITLE
pkg installation instructions

### ISSUE THREAD

**Issue by kose-y** [OpenMendel/LangeSymposium-ProgrammingWorkshop-20202022#2]
@biona001 
I think the best way to include pkg installation commands in jupyter notebooks would be using the string macro `pkg"..."`. 

For example:
```julia
using Pkg
pkg"add https://github.com/OpenMendel/SnpArrays.jl"
pkg"add https://github.com/OpenMendel/MendelSearch.jl"
pkg"add https://github.com/OpenMendel/MendelBase.jl"
pkg"add https://github.com/OpenMendel/MendelIHT.jl"
```

The commands can all run in a single cell.

This feature is last documented in https://docs.julialang.org/en/v1.1/stdlib/Pkg/, and still works in v1.2.0. I'm not sure why it's no longer included in the main Julia documentation. I don't think it's even deprecated.

**Comment by biona001** [comment]
Oh didn't know that existed, thanks. But we just agreed that we won't include package installation instructions in the notebooks since we're running everything on binders. Good for future reference though!
