### ISSUE TITLE
Heritability estimation not correct?

### ISSUE THREAD

**Issue by biona001** [OpenMendel/LangeSymposium-ProgrammingWorkshop-20202022#3]
Sorry for the very late question. Asking here instead of VarianceComponentModels.jl because the phenotypes here are simulated. 

According to box 17 of the [tutorial](https://openmendel.github.io/LangeSymposium-ProgrammingWorkshop-20202022/03-varcomp/VarianceComponentModels.html), the estimated heritability is 0.573. But isn't the phenotype simulated with sigma_a = 0.1 and sigma_e = 0.9 (box 8)? So shouldn't heritability be around 0.1? Did I miss something?

**Comment by KennethLange** [comment]
Ben,

I’m also confused. Ask Juhyun.

Ken

**Comment by biona001** [comment]
@juhkim111 do you have any idea? It's no worries if you don't know, just want to check if I made any stupid mistake.

**Comment by biona001** [comment]
So I ran the notebook myself (and re-simulated the phenotypes using the commented out code), and got 
```
(σ2a, σ2e) = (0.14918482888871162, 0.7752749147469098)
```
and heritability is ` 0.16137514901623803`:
```julia
julia> h, hse = heritability(trait_model.Σ, Σcov)
julia> [h[1], hse[1]]

2-element Array{Float64,1}:
 0.16137514901623803
 0.5184047559798852
```
So it makes sense. Sorry, I should have run things myself first.
